name: Release

on:
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Windows
        run: npm run build:win

      - name: Rename Windows artifact
        run: mv dist/koclauncher-setup.exe Knockoutcitylauncher-Setup.exe

      - name: Upload Windows binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Knockoutcitylauncher-Setup.exe
          asset_name: Knockoutcitylauncher-Setup.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is the Windows release"

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Linux
        run: npm run build:linux

      - name: Rename Linux artifact
        run: mv dist/koclauncher.AppImage Knockoutcitylauncher.AppImage

      - name: Upload Linux binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Knockoutcitylauncher.AppImage
          asset_name: Knockoutcitylauncher.AppImage
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is the Linux release"
